DEBUG 2021-12-14 20:39:00.625 UTC: 	 CRAB Client version: v3.211130
DEBUG 2021-12-14 20:39:00.625 UTC: 	 Running on: Linux sbgui5.in2p3.fr 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-12-14 20:39:00.625 UTC: 	 Executing command: 'status'
DEBUG 2021-12-14 20:39:00.626 UTC: 	 Found CRAB cache file /home/msessini/.crab3
ERROR 2021-12-14 20:39:00.630 UTC: 	 Error: --verboseErrors is not a valid CRAB project directory.
ERROR 2021-12-14 20:39:00.630 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: --verboseErrors is not a valid CRAB project directory.
INFO 2021-12-14 20:39:00.635 UTC: 	 Log file is /grid_mnt/opt__sbg__cms__safe1/cms/msessini/CMSSW_10_2_23/src/LLRHiggsTauTau/NtupleProducer/test/crab.log
